import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const EMPTY={documents:[],total_chunks:0,history:[],feedback:{}};
const DEFAULTS={top_k:5,budget:10,retrieval:'dense',verifier:'semantic',generator:'offline',model:'',ocr:true};
const labels={documents:'Documents',assistant:'Assistant',activity:'Activity',settings:'Settings'};
const readable=value=>(value||'').replaceAll('_',' ');

async function api(path,options={}) {
  const response=await fetch(`/api${path}`,{...options,headers:{'X-ADI-Request':'1',...options.headers}});
  if(!response.ok){let message=`Request failed (${response.status})`;try{const data=await response.json();message=typeof data.detail==='string'?data.detail:message;}catch{}throw new Error(message);}
  return response.json();
}
function Icon({name,size=20}) {
  const paths={file:<><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6M8 13h8M8 17h5"/></>,upload:<><path d="M12 16V3m-5 5 5-5 5 5M4 16v4h16v-4"/></>,chat:<path d="M21 11a8 8 0 0 1-8 8H7l-5 3V11a9 9 0 0 1 19 0Z"/>,arrow:<path d="M4 12h16m-6-6 6 6-6 6"/>,check:<path d="m5 12 4 4L19 6"/>,settings:<><path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="3"/><circle cx="16" cy="17" r="3"/></>,activity:<path d="M2 12h4l3-8 6 16 3-8h4"/>,close:<path d="m6 6 12 12M6 18 18 6"/>,trash:<><path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7"/></>};
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.file}</svg>;
}
function App(){
  const [theme,setTheme]=useState(()=>localStorage.getItem('adi-theme')||'dark');
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('adi-theme',theme);},[theme]);
  const [tab,setTab]=useState('documents'),[workspace,setWorkspace]=useState(EMPTY),[settings,setSettings]=useState(DEFAULTS);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [files,setFiles]=useState([]),[question,setQuestion]=useState(''),[scope,setScope]=useState(''),[selected,setSelected]=useState(null);
  const [drag,setDrag]=useState(false),[resetOpen,setResetOpen]=useState(false),[inspector,setInspector]=useState(null);
  const input=useRef(null);
  useEffect(()=>{api('/workspace').then(setWorkspace).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
  const answer=workspace.history.find(a=>a.id===selected)||workspace.history.at(-1);
  const locked=loading||Boolean(busy);
  function chooseFiles(incoming){
    setError('');const items=Array.from(incoming);
    if(items.some(f=>!f.name.toLowerCase().endsWith('.pdf'))){setError('Please choose PDF files only.');return;}
    if(items.some(f=>f.size>25*1024*1024)||items.length>10||items.reduce((s,f)=>s+f.size,0)>100*1024*1024){setError('Choose up to 10 PDFs: 25 MB per file, 100 MB total.');return;}
    setFiles(items);
  }
  async function processDocuments(){
    setBusy('Reading PDFs and building your document index. The first run may download local models…');setError('');setNotice('');
    const data=new FormData();files.forEach(f=>data.append('files',f));data.append('ocr',settings.ocr);
    try{setWorkspace(await api('/documents',{method:'POST',body:data}));setFiles([]);if(input.current)input.current.value='';setScope('');setSelected(null);setInspector(null);setNotice('Your documents are ready. Open Assistant to ask a question.');}
    catch(e){setError(e.message);}finally{setBusy('');}
  }
  async function ask(event){
    event.preventDefault();if(!question.trim()||locked)return;
    setBusy('Finding evidence, checking claims, and recovering missing support…');setError('');setNotice('');
    try{const result=await api('/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...settings,question,document_id:scope||null})});setWorkspace(w=>({...w,history:[...w.history,result].slice(-50)}));setSelected(result.id);}
    catch(e){setError(e.message);}finally{setBusy('');}
  }
  async function reset(){setResetOpen(false);setBusy('Clearing workspace…');setError('');try{setWorkspace(await api('/workspace',{method:'DELETE'}));setScope('');setSelected(null);setInspector(null);setNotice('Workspace cleared.');}catch(e){setError(e.message);}finally{setBusy('');}}
  async function inspect(doc){setError('');setBusy('Opening document text…');try{const chunks=await api(`/documents/${encodeURIComponent(doc.document_id)}/chunks`);setInspector({doc,chunks});}catch(e){setError(e.message);}finally{setBusy('');}}
  async function rate(rating){if(!answer)return;setBusy('Saving feedback…');setError('');try{await api(`/answers/${answer.id}/feedback`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rating})});setWorkspace(w=>({...w,feedback:{...w.feedback,[answer.id]:{rating}}}));setNotice('Feedback saved.');}catch(e){setError(e.message);}finally{setBusy('');}}
  function exportSession(){const blob=new Blob([JSON.stringify(workspace,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='document-workspace.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function update(key,value){setSettings(s=>({...s,[key]:value}));}
  return <div className="app-shell">
    <a className="skip-link" href="#workspace">Skip to workspace</a>
    <header className="topbar"><a className="brand" href="#" onClick={()=>setTab('documents')}><span className="brand-icon"><Icon name="file"/></span><span>Agentic<span className="brand-sub">Document Intelligence</span></span></a><div className="header-actions"><span className="header-note">A little more clarity.<span className="yellow-dot"/></span><button className="theme-toggle" type="button" onClick={()=>setTheme(t=>t==='dark'?'light':'dark')} aria-label={`Switch to ${theme==='dark'?'light':'dark'} mode`}><span className="theme-toggle-track"><span className="theme-icon">☀</span><span className="theme-icon">☾</span><span className="theme-toggle-thumb"/></span></button></div></header>
    <main>
      <section className="hero"><div className="hero-art topic-art" role="img" aria-label="Animated dark glass illustration of agentic document intelligence with RAG retrieval, verified evidence and cited answers">
<div className="meaning-orbit meaning-orbit-one"/><div className="meaning-orbit meaning-orbit-two"/><div className="meaning-glow"/>
<div className="meaning-docs" aria-hidden="true"><span className="doc-back">TXT</span><span className="doc-mid">W</span><span className="doc-front">PDF</span></div>
<div className="meaning-core"><span className="core-ring"/><span className="core-file"><Icon name="file" size={25}/></span></div>
<div className="meaning-step step-upload"><span className="step-number">1</span><Icon name="upload" size={17}/><span><strong>Upload Documents</strong><small>PDF · DOCX · TXT</small></span></div>
<div className="meaning-step step-retrieve"><span className="step-number">2</span><span className="step-glyph">⌕</span><span><strong>Retrieve Evidence</strong><small>Find relevant information</small></span></div>
<div className="meaning-step step-verify"><span className="step-number">3</span><Icon name="check" size={18}/><span><strong>Verify Claims</strong><small>Check sources & evidence</small></span></div>
<div className="meaning-step step-answer"><span className="step-number">4</span><Icon name="file" size={17}/><span><strong>Clear Answer</strong><small>Cited and reliable</small></span></div>
<div className="meaning-answer"><div className="answer-head"><strong>Answer</strong><span>✓ verified</span></div><i/><i/><i/><div className="answer-cites"><b>Citations</b><span>1</span><span>2</span><span>3</span></div></div>
<div className="meaning-path path-a"/><div className="meaning-path path-b"/><div className="meaning-path path-c"/><div className="meaning-path path-d"/>
<div className="meaning-sparks"><i/><i/><i/><i/><i/></div>
</div><p className="eyebrow"><span/> YOUR KNOWLEDGE, CONNECTED</p><h1>Make room<br/>for <em>clear answers.</em></h1><p className="hero-copy">Turn your documents into a conversation.<br/>Find answers, check the evidence, and keep the source in sight.</p><button className="text-button" onClick={()=>document.getElementById('workspace').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}>Explore your workspace <Icon name="arrow" size={17}/></button></section>
      <section className="workspace" id="workspace" aria-label="Document workspace">
        <div className="workspace-header"><nav aria-label="Workspace sections">{Object.entries(labels).map(([key,label])=><button key={key} aria-current={tab===key?'page':undefined} className={tab===key?'nav-item active':'nav-item'} onClick={()=>{setTab(key);setNotice('');}}><Icon name={{documents:'file',assistant:'chat',activity:'activity',settings:'settings'}[key]} size={17}/>{label}</button>)}</nav><span className="document-count">{workspace.documents.length} document{workspace.documents.length!==1?'s':''}</span></div>
        <div className="workspace-body">
          {error&&<div className="notice error" role="alert"><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><Icon name="close" size={16}/></button></div>}
          {notice&&<div className="notice success" role="status">{notice}</div>}
          {(busy||loading)&&<div className="notice progress" role="status"><span className="spinner"/>{busy||'Opening your workspace…'}</div>}
          {tab==='documents'&&<>
            <div className="section-heading"><div><p className="eyebrow small">START WITH YOUR SOURCES</p><h2>Your document space</h2><p>Bring the PDFs. We’ll help you find what matters.</p></div>{workspace.documents.length>0&&<button className="secondary" disabled={locked} onClick={()=>setTab('assistant')}>Ask a question <Icon name="arrow" size={16}/></button>}</div>
            <div className={`dropzone ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();if(!locked)setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(!locked)chooseFiles(e.dataTransfer.files);}}>
              <span className="upload-icon"><Icon name="upload" size={25}/></span><h3>Drop your documents here</h3><p>English PDFs, including scanned pages · Up to 25 MB each</p><input ref={input} type="file" id="pdf-input" className="visually-hidden" accept="application/pdf,.pdf" multiple disabled={locked} onChange={e=>chooseFiles(e.target.files)} aria-label="Select PDF files"/><button className="secondary" disabled={locked} onClick={()=>input.current.click()}>Browse files</button>
            </div>
            {files.length>0&&<div className="pending-files"><ul>{files.map((f,i)=><li key={i}><Icon name="file" size={16}/><span>{f.name}</span><small>{(f.size/1024/1024).toFixed(1)} MB</small><button disabled={locked} aria-label={`Remove ${f.name}`} onClick={()=>setFiles(fs=>fs.filter((_,j)=>j!==i))}><Icon name="close" size={16}/></button></li>)}</ul><div className="upload-actions"><p>{workspace.documents.length?'Processing these files replaces your current documents and answer history.':'Your sources stay in this server workspace.'}</p><button className="primary" disabled={locked} onClick={processDocuments}>Process {files.length} PDF{files.length>1?'s':''}<Icon name="arrow" size={17}/></button></div></div>}
            {workspace.documents.length>0&&<div className="documents-list"><div className="list-title"><h3>Ready to explore</h3><span>{workspace.total_chunks} searchable passages</span></div>{workspace.documents.map(doc=><article className="document-row" key={doc.document_id}><span className="file-icon"><Icon name="file"/></span><div className="doc-name"><strong>{doc.filename.replace(/^\d{3}_/,'')}</strong><small>{doc.page_count} pages · {doc.chunk_count} passages{doc.ocr_page_count>0?` · ${doc.ocr_page_count} OCR pages`:''}</small>{doc.warnings.map((w,i)=><small className="warning" key={i}>{w}</small>)}</div><button className="secondary compact" disabled={locked} onClick={()=>inspect(doc)}>Inspect</button><a className="source-link" href={`/api/documents/${encodeURIComponent(doc.document_id)}/source`} target="_blank" rel="noreferrer">Open PDF ↗</a></article>)}</div>}
            {inspector&&<div className="inspector"><div className="list-title"><h3>Extracted text · {inspector.doc.filename.replace(/^\d{3}_/,'')}</h3><button aria-label="Close extracted text" onClick={()=>setInspector(null)}><Icon name="close"/></button></div>{inspector.chunks.map(c=><details key={c.chunk_id}><summary>Page {c.page_number||'—'} · {c.word_count} words</summary><p className="preserve">{c.text}</p></details>)}</div>}
          </>}
          {tab==='assistant'&&<>
            <div className="section-heading"><div><p className="eyebrow small">FOLLOW THE EVIDENCE</p><h2>A conversation with your documents</h2><p>Each answer comes with sources and claim checks.</p></div></div>
            {!workspace.documents.length?<div className="empty-state"><Icon name="chat" size={32}/><h3>Every answer starts with a source.</h3><p>Add your PDFs first, then ask your first question.</p><button className="primary" onClick={()=>setTab('documents')}>Add documents <Icon name="arrow" size={17}/></button></div>:<>
              <form onSubmit={ask} className="question-form"><label htmlFor="scope">Search in</label><select id="scope" value={scope} disabled={locked} onChange={e=>setScope(e.target.value)}><option value="">All documents</option>{workspace.documents.map(d=><option key={d.document_id} value={d.document_id}>{d.filename.replace(/^\d{3}_/,'')}</option>)}</select><label htmlFor="question">Your question</label><textarea id="question" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What are the main findings in these documents?" rows={3} maxLength={4000} disabled={locked}/><div className="form-footer"><small>Answers may be partial when evidence is missing.</small><button className="primary" disabled={locked||!question.trim()}>Ask your documents <Icon name="arrow" size={17}/></button></div></form>
              {workspace.history.length>1&&<label className="history-picker">Previous questions<select value={answer?.id||''} onChange={e=>setSelected(e.target.value)}>{[...workspace.history].reverse().map(a=><option value={a.id} key={a.id}>{a.question}</option>)}</select></label>}
              {answer&&<div className="answer-layout"><article className="answer-panel"><div className="list-title"><h3>Your answer</h3><span className={`badge ${answer.final_verification_status==='verified'?'verified':''}`}>{readable(answer.final_verification_status)}</span></div><p className="question-echo">{answer.question}</p><p className="answer-text">{answer.final_answer}</p><small className="muted">{readable(answer.status)} · {answer.latency_seconds}s · {answer.rounds_used} recovery rounds</small><div className="claim-list"><h4>Claim checks</h4>{answer.verifications?.length?answer.verifications.map(v=><details key={v.claim_id}><summary><span className={`claim-dot ${v.status}`}/>{v.claim_id} · {readable(v.status)}</summary><p>{v.claim_text}</p><p className="muted">{v.reason}</p><small>{v.verifier_method} · Support score: {v.support_score.toFixed(2)}</small></details>):<p className="muted">No claims available to verify.</p>}</div>{answer.steps?.length>0&&<details><summary>Recovery activity ({answer.steps.length})</summary>{answer.steps.map((s,i)=><p key={i}>Round {s.round_index} · {readable(s.action)}<br/><small>{s.query}</small></p>)}</details>}<div className="feedback"><span>Was this helpful?</span>{[['useful','Useful'],['needs_review','Needs review'],['incorrect','Incorrect']].map(([value,label])=><button className={workspace.feedback[answer.id]?.rating===value?'selected':''} disabled={locked} key={value} onClick={()=>rate(value)}>{label}</button>)}</div></article><aside className="evidence-panel"><p className="eyebrow small">BACK TO THE SOURCE</p><h3>Supporting evidence</h3>{answer.citations?.length?answer.citations.map(c=><details key={c.label} open><summary><span className="citation-label">[{c.label}]</span> {workspace.documents.find(d=>d.document_id===c.document_id)?.filename.replace(/^\d{3}_/,'')||'Document'}{c.page_number?` · p. ${c.page_number}`:''}</summary><p>{c.text}</p><a href={`/api/documents/${encodeURIComponent(c.document_id)}/source#page=${c.page_number||1}`} target="_blank" rel="noreferrer">View original ↗</a></details>):<p className="muted">No supporting passages were found for this answer.</p>}</aside></div>}
            </>}
          </>}
          {tab==='activity'&&<><div className="section-heading"><div><p className="eyebrow small">YOUR WORKSPACE AT A GLANCE</p><h2>Activity</h2><p>Real results from this session.</p></div><button className="secondary" disabled={locked||!workspace.history.length} onClick={exportSession}>Export session</button></div><div className="metrics">{[['Questions',workspace.history.length],['Citations',workspace.history.reduce((n,a)=>n+(a.citations?.length||0),0)],['Supported claims',workspace.history.reduce((n,a)=>n+(a.verifications?.filter(v=>v.status==='supported').length||0),0)]].map(([name,value])=><div key={name}><span>{name}</span><strong>{value}</strong></div>)}</div>{!workspace.history.length?<div className="empty-state"><Icon name="activity" size={30}/><h3>Your research trail starts here.</h3><p>Ask a question to see your answers and sources.</p></div>:<div className="activity-list">{[...workspace.history].reverse().map(a=><button key={a.id} onClick={()=>{setSelected(a.id);setTab('assistant');}}><span><strong>{a.question}</strong><small>{readable(a.final_verification_status)} · {a.latency_seconds}s</small></span><Icon name="arrow"/></button>)}</div>}</>}
          {tab==='settings'&&<><div className="section-heading"><div><p className="eyebrow small">MAKE IT WORK FOR YOU</p><h2>Workspace settings</h2><p>Applied to the next question or document upload.</p></div></div><fieldset disabled={locked} className="settings-grid"><label>Answer generation<select value={settings.generator} onChange={e=>update('generator',e.target.value)}><option value="offline">Free extractive answers</option><option value="local">Local language model</option></select><small>Extractive mode selects text from your sources. A local model requires Ollama or LM Studio on the server.</small></label>{settings.generator==='local'&&<label>Local model name<input value={settings.model} onChange={e=>update('model',e.target.value)} placeholder="e.g. qwen2.5:3b"/><small>The local endpoint is configured on the Python server.</small></label>}<label>Evidence retrieval<select value={settings.retrieval} onChange={e=>update('retrieval',e.target.value)}><option value="dense">Semantic search · BGE</option><option value="hybrid">Hybrid semantic + keyword</option><option value="reranked">Hybrid with reranking</option></select></label><label>Claim verification<select value={settings.verifier} onChange={e=>update('verifier',e.target.value)}><option value="semantic">Semantic NLI</option><option value="lexical">Lexical baseline</option></select><small>Semantic checks may download a model on first use.</small></label><label>Evidence passages: {settings.top_k}<input type="range" min="1" max="10" value={settings.top_k} onChange={e=>update('top_k',Number(e.target.value))}/></label><label>Recovery budget: {settings.budget} passages<input type="range" min="2" max="20" value={settings.budget} onChange={e=>update('budget',Number(e.target.value))}/></label><label className="checkbox-label"><input type="checkbox" checked={settings.ocr} onChange={e=>update('ocr',e.target.checked)}/><span>Read scanned pages with OCR<small>Requires local Tesseract. Applies to the next upload.</small></span></label></fieldset><div className="reset-row"><div><h3>Clear this workspace</h3><p>Remove the uploaded PDFs, index, answers and feedback from this session.</p></div><button className="danger" disabled={locked||!workspace.documents.length} onClick={()=>setResetOpen(true)}><Icon name="trash" size={16}/>Clear workspace</button></div></>}
        </div>
      </section>
    </main>
    <footer><span>Agentic Document Intelligence</span><span>Built around your sources.</span></footer>
    {resetOpen&&<div className="modal-backdrop" onKeyDown={e=>{if(e.key==='Escape')setResetOpen(false);}}><div role="alertdialog" aria-modal="true" aria-labelledby="reset-title" className="modal"><h2 id="reset-title">Clear your workspace?</h2><p>This removes your session’s documents and answers.</p><div><button className="secondary" autoFocus onClick={()=>setResetOpen(false)}>Keep workspace</button><button className="danger" onClick={reset}>Clear workspace</button></div></div></div>}
  </div>
}
createRoot(document.getElementById('root')).render(<App/>);
